Often, file transfers remain untested in many applications. In this section, you will see how
easy is to test that the file downloads but also that the downloaded file contents match our expectations.

Micronaut is test framework agnostic. For this tutorial, we use http://spockframework.org/[Spock Framework]. Additionally, we use Geb; a browser automation solution.

To use Geb, add dependencies:

[source, groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=geb,indent=0]
----

Create a Geb Configuration file. We configure some chrome options to control the download path.

[source, groovy]
.src/test/resources/GebConfig.groovy
----
include::{sourceDir}/src/test/resources/GebConfig.groovy[]
----

<1> Disable confirmation popups
<2> Configure the download folder

Geb uses the Page concept pattern - The Page Object Pattern gives us a common sense way to model content in a reusable and maintainable way. Create a Geb Page to encapsulate the Excel link:

[source, groovy]
.src/test/groovy/example/micronaut/HomePage.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/HomePage.groovy[]
----

include::{commondir}/common-webdriverbinaries.adoc[]

<1> Pass system property `geb.env` to the tests.
<2> Pass system property `download.folder` to the tests.

Create a test which verifies the Excel file is downloaded and the content matches our expectations.

[source, groovy]
.src/test/groovy/example/micronaut/DownloadExcelSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/DownloadExcelSpec.groovy[]
----

<1> Annotate the class with `@MicronatTest` to let Micronaut starts the embedded server and inject the beans. More info: https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html]
<2> Inject the Embedded Server.
<3> The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port. We use this port to set http://www.gebish.org/manual/current/#base-url[Geb base url].

To run the tests:

[source,bash]
----
$ ./gradlew -Dgeb.env=chrome -Ddownload.folder=/Users/sdelamo/Downloads test
$ open build/reports/tests/test/index.html
----
